### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Ibot02** [cpw/compactsolars#1]
MultiMC Console:

Instance started with command: "C:\Program Files\Java\jre7\bin\java.exe"  -Xmx1024m -Xms512m -cp "D:\MultiMC" -jar MultiMCLauncher.jar "D:\MultiMC\instances\Rails+Stuff\.minecraft\" "Ibot02" "-7160956993221770857" "MultiMC: Rails+Stuff" "max"

Loading jars...
Loading URL: file:/D:/MultiMC/instances/Rails+Stuff/.minecraft/bin/minecraft.jar
Loading URL: file:/D:/MultiMC/instances/Rails+Stuff/.minecraft/bin/lwjgl.jar
Loading URL: file:/D:/MultiMC/instances/Rails+Stuff/.minecraft/bin/lwjgl_util.jar
Loading URL: file:/D:/MultiMC/instances/Rails+Stuff/.minecraft/bin/jinput.jar
Loading natives...
Fixed Minecraft Path: Field was private static java.io.File net.minecraft.client.Minecraft.am
MCDIR: C:\Users\Tobi\AppData\Roaming.minecraft
Launching with applet wrapper...
2012-09-17 17:35:26 [INFO] [ForgeModLoader] Forge Mod Loader version 3.0.165.344 for Minecraft client:1.3.2, server:1.3.2 loading
2012-09-17 17:35:26 [INFO] [STDOUT] Adding Accesstransformer map: codechickencore_at.cfg
2012-09-17 17:35:26 [INFO] [STDOUT] Adding Accesstransformer map: nei_at.cfg
2012-09-17 17:35:26 [INFO] [STDOUT] Inserted super call into aqu.c
2012-09-17 17:35:26 [INFO] [STDOUT] aqh was overriden from NotEnoughItems 1.4.0.0.jar
2012-09-17 17:35:27 [INFO] [STDOUT] Generated BlockMobSpawner helper method.
2012-09-17 17:35:27 [INFO] [STDOUT] 27 achievements
2012-09-17 17:35:28 [INFO] [STDOUT] 195 recipes
2012-09-17 17:35:28 [INFO] [STDOUT] Setting user: Ibot02, -7160956993221770857
2012-09-17 17:35:28 [INFO] [STDOUT] LWJGL Version: 2.4.2
2012-09-17 17:35:29 [INFO] [ForgeModLoader] Attempting early MinecraftForge initialization
2012-09-17 17:35:29 [INFO] [ForgeModLoader] Completed early MinecraftForge initialization
2012-09-17 17:35:29 [INFO] [ForgeModLoader] Searching D:\MultiMC\instances\Rails+Stuff.minecraft\mods for mods
2012-09-17 17:35:29 [INFO] [ForgeModLoader] The mod container CodeChickenCore 0.6.0.jar appears to be missing an mcmod.info file
2012-09-17 17:35:29 [INFO] [ForgeModLoader] The mod container NotEnoughItems 1.4.0.0.jar appears to be missing an mcmod.info file
2012-09-17 17:35:29 [WARNING] [ForgeModLoader] Mod CompactSolars is missing the required element 'version'. Falling back to metadata version 3.0.1.13
2012-09-17 17:35:29 [WARNING] [ForgeModLoader] Mod CompactSolars is missing the required element 'version' and no fallback can be found. Substituting '1.0'.
2012-09-17 17:35:29 [INFO] [ForgeModLoader] The mod container NEI_BuildcraftPlugin 1.1.0.7.zip appears to be missing an mcmod.info file
2012-09-17 17:35:29 [INFO] [ForgeModLoader] The mod container NEI_ForestryPlugin 1.2.0.26.zip appears to be missing an mcmod.info file
2012-09-17 17:35:29 [INFO] [ForgeModLoader] The mod container NEI_RailCraftPlugin 1.4.0.8.zip appears to be missing an mcmod.info file
2012-09-17 17:35:29 [INFO] [ForgeModLoader] Forge Mod Loader has identified 21 mods to load
2012-09-17 17:35:31 [WARNING] [ForgeModLoader] The mod id ModularForceFieldSystem attempted to register channels without specifying a packet handler
2012-09-17 17:35:31 [INFO] [STDOUT] Loaded Universal Electricity Mod: Basic Componenets
2012-09-17 17:35:31 [INFO] [ForgeModLoader] [Mystcraft] Adding Entity Renderers
2012-09-17 17:35:33 [WARNING] [ForgeModLoader] BuildCraft: Using outdated version [3.2.0pre7 (build:3)] for Minecraft 1.3.2. Consider updating.
2012-09-17 17:35:33 [INFO] [Buildcraft] Starting BuildCraft 3.2.0pre7 (:3)
2012-09-17 17:35:33 [INFO] [Buildcraft] Copyright (c) SpaceToad, 2011
2012-09-17 17:35:33 [INFO] [Buildcraft] http://www.mod-buildcraft.com
2012-09-17 17:35:34 [WARNING] [ForgeModLoader] Forestry: Using outdated version for Minecraft 1.3.2. Consider updating.
2012-09-17 17:35:34 [INFO] [STDOUT] Loaded Universal Electricity Mod: ICBM
2012-09-17 17:35:34 [INFO] [ForgeModLoader] MinecraftForge v4.0.0.241 Initialized
2012-09-17 17:35:34 [INFO] [STDOUT] MinecraftForge v4.0.0.241 Initialized
[IC2] Config loaded from D:\MultiMC\instances\Rails+Stuff.minecraft\config\IC2.cfg
2012-09-17 17:35:34 [INFO] [STDOUT] [IC2] Using 32 audio sources.
2012-09-17 17:35:36 [INFO] [ForgeModLoader] [Railcraft] An updated version of Railcraft is available: 6.1.2.0
2012-09-17 17:35:36 [SEVERE] [ForgeModLoader] Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
2012-09-17 17:35:36 [SEVERE] [ForgeModLoader] 
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized
    mod_CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized
    mod_NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized
    BasicComponenets [Basic Componenets](Universal Electricity_v0.7.0.86.zip) Unloaded->Constructed->Pre-initialized
    Mystcraft [Mystcraft](minecraft.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Core [BuildCraft](buildcraft-A-3.2.0pre7.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Builders [BC Builders](buildcraft-A-3.2.0pre7.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Energy [BC Energy](buildcraft-A-3.2.0pre7.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Factory [BC Factory](buildcraft-A-3.2.0pre7.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Transport [BC Transport](buildcraft-A-3.2.0pre7.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Silicon [BC Silicon](buildcraft-A-3.2.0pre7.jar) Unloaded->Constructed->Pre-initialized
    Forestry [Forestry for Minecraft](forestry-A-1.5.0.2.jar) Unloaded->Constructed->Pre-initialized
    ICBM [ICBM](ICBM_v0.5.3.zip) Unloaded->Constructed->Pre-initialized
    IC2 [IndustrialCraft 2](industrialcraft-2_1.106.jar) Unloaded->Constructed->Pre-initialized
    LogisticsPipes|Main [Logistics Pipes](LogisticsPipes-0.5.1.pre3.jar) Unloaded->Constructed->Pre-initialized
    CompactSolars [Compact Solar Arrays](mod_compactsolars-main-3.0.1.13.zip) Unloaded->Constructed->Errored
    IronChest [Iron Chest](mod_ironchests-client-4.0.2.44.zip) Unloaded->Constructed->Pre-initialized
    ModularForceFieldSystem [Modular ForceField System V2](ModularForceFieldSystemV2.1.7.0.12.zip) Unloaded->Constructed->Pre-initialized
    Railcraft [Railcraft](Railcraft_6.1.1.0.zip) Unloaded->Constructed->Pre-initialized
    UniversalElectricity [Universal Electricity](Universal Electricity_v0.7.0.86.zip) Unloaded->Constructed->Pre-initialized
2012-09-17 17:35:36 [SEVERE] [ForgeModLoader] The following problems were captured during this phase
2012-09-17 17:35:36 [SEVERE] [ForgeModLoader] Caught exception from CompactSolars
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:371)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:81)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:444)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:141)
    at net.minecraft.client.Minecraft.a(Minecraft.java:405)
    at net.minecraft.client.Minecraft.run(Minecraft.java:737)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: cpw.mods.fml.common.event.FMLPreInitializationEvent.getVersionProperties()Ljava/util/Properties;
    at cpw.mods.compactsolars.CompactSolars.preInit(CompactSolars.java:44)
    ... 29 more
2012-09-17 17:35:46 [INFO] [STDERR] cpw.mods.fml.common.LoaderException: java.lang.reflect.InvocationTargetException
2012-09-17 17:35:46 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.transition(LoadController.java:102)
2012-09-17 17:35:46 [INFO] [STDERR]     at cpw.mods.fml.common.Loader.loadMods(Loader.java:445)
2012-09-17 17:35:46 [INFO] [STDERR]     at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:141)
2012-09-17 17:35:46 [INFO] [STDERR]     at net.minecraft.client.Minecraft.a(Minecraft.java:405)
2012-09-17 17:35:46 [INFO] [STDERR]     at net.minecraft.client.Minecraft.run(Minecraft.java:737)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.lang.Thread.run(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR] Caused by: java.lang.reflect.InvocationTargetException
2012-09-17 17:35:46 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-09-17 17:35:46 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:371)
2012-09-17 17:35:46 [INFO] [STDERR]     at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
2012-09-17 17:35:46 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2012-09-17 17:35:46 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
2012-09-17 17:35:46 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
2012-09-17 17:35:46 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:268)
2012-09-17 17:35:46 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:124)
2012-09-17 17:35:46 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-09-17 17:35:46 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
2012-09-17 17:35:46 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2012-09-17 17:35:46 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
2012-09-17 17:35:46 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
2012-09-17 17:35:46 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:268)
2012-09-17 17:35:46 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:81)
2012-09-17 17:35:46 [INFO] [STDERR]     at cpw.mods.fml.common.Loader.loadMods(Loader.java:444)
2012-09-17 17:35:46 [INFO] [STDERR]     ... 4 more
2012-09-17 17:35:46 [INFO] [STDERR] Caused by: java.lang.NoSuchMethodError: cpw.mods.fml.common.event.FMLPreInitializationEvent.getVersionProperties()Ljava/util/Properties;
2012-09-17 17:35:46 [INFO] [STDERR]     at cpw.mods.compactsolars.CompactSolars.preInit(CompactSolars.java:44)
2012-09-17 17:35:46 [INFO] [STDERR]     ... 29 more
2012-09-17 17:35:46 [INFO] [STDERR] Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: component argument pData
2012-09-17 17:35:46 [INFO] [STDERR]     at sun.java2d.windows.GDIWindowSurfaceData.initOps(Native Method)
2012-09-17 17:35:46 [INFO] [STDERR]     at sun.java2d.windows.GDIWindowSurfaceData.<init>(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at sun.java2d.windows.GDIWindowSurfaceData.createData(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at sun.java2d.d3d.D3DScreenUpdateManager.getGdiSurface(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at sun.java2d.d3d.D3DScreenUpdateManager.createGraphics(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at sun.awt.windows.WComponentPeer.getGraphics(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.awt.Component.getGraphics(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at sun.awt.RepaintArea.paint(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at sun.awt.windows.WComponentPeer.handleEvent(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.awt.Component.dispatchEventImpl(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.awt.Container.dispatchEventImpl(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.awt.Component.dispatchEvent(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.awt.EventQueue.access$000(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.awt.EventQueue$3.run(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.awt.EventQueue$3.run(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.security.AccessController.doPrivileged(Native Method)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.awt.EventQueue$4.run(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.awt.EventQueue$4.run(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.security.AccessController.doPrivileged(Native Method)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.awt.EventQueue.dispatchEvent(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
2012-09-17 17:35:46 [INFO] [STDERR]     at java.awt.EventDispatchThread.run(Unknown Source)

Minecraft Crash Report

```
  Minecraft has crashed!      
  ----------------------      
```

Minecraft has stopped running because it encountered a problem; Failed to start game
This error has been saved to D:\MultiMC\instances\Rails+Stuff.minecraft\crash-reports\crash-2012-09-17_17.35.46-client.txt for your convenience. Please include a copy of this file if you report this crash to anyone.

--- BEGIN ERROR REPORT 6e22c635 --------
Generated 17.09.12 17:35
- Minecraft Version: 1.3.2
- Operating System: Windows 7 (amd64) version 6.1
- Java Version: 1.7.0_04, Oracle Corporation
- Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
- Memory: 436795768 bytes (416 MB) / 514523136 bytes (490 MB) up to 954466304 bytes (910 MB)
- JVM Flags: 2 total; -Xmx1024m -Xms512m
- FML: FML v3.0.165.344 Minecraft Forge 4.0.0.241 21 mods loaded, 21 mods active
  FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized
  Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized
  mod_CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized
  mod_NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized
  BasicComponenets [Basic Componenets](Universal Electricity_v0.7.0.86.zip) Unloaded->Constructed->Pre-initialized
  Mystcraft [Mystcraft](minecraft.jar) Unloaded->Constructed->Pre-initialized
  BuildCraft|Core [BuildCraft](buildcraft-A-3.2.0pre7.jar) Unloaded->Constructed->Pre-initialized
  BuildCraft|Builders [BC Builders](buildcraft-A-3.2.0pre7.jar) Unloaded->Constructed->Pre-initialized
  BuildCraft|Energy [BC Energy](buildcraft-A-3.2.0pre7.jar) Unloaded->Constructed->Pre-initialized
  BuildCraft|Factory [BC Factory](buildcraft-A-3.2.0pre7.jar) Unloaded->Constructed->Pre-initialized
  BuildCraft|Transport [BC Transport](buildcraft-A-3.2.0pre7.jar) Unloaded->Constructed->Pre-initialized
  BuildCraft|Silicon [BC Silicon](buildcraft-A-3.2.0pre7.jar) Unloaded->Constructed->Pre-initialized
  Forestry [Forestry for Minecraft](forestry-A-1.5.0.2.jar) Unloaded->Constructed->Pre-initialized
  ICBM [ICBM](ICBM_v0.5.3.zip) Unloaded->Constructed->Pre-initialized
  IC2 [IndustrialCraft 2](industrialcraft-2_1.106.jar) Unloaded->Constructed->Pre-initialized
  LogisticsPipes|Main [Logistics Pipes](LogisticsPipes-0.5.1.pre3.jar) Unloaded->Constructed->Pre-initialized
  CompactSolars [Compact Solar Arrays](mod_compactsolars-main-3.0.1.13.zip) Unloaded->Constructed->Errored
  IronChest [Iron Chest](mod_ironchests-client-4.0.2.44.zip) Unloaded->Constructed->Pre-initialized
  ModularForceFieldSystem [Modular ForceField System V2](ModularForceFieldSystemV2.1.7.0.12.zip) Unloaded->Constructed->Pre-initialized
  Railcraft [Railcraft](Railcraft_6.1.1.0.zip) Unloaded->Constructed->Pre-initialized
  UniversalElectricity [Universal Electricity](Universal Electricity_v0.7.0.86.zip) Unloaded->Constructed->Pre-initialized
- LWJGL: 2.4.2
- OpenGL: ATI Radeon HD 5450   GL version 3.1.9210, ATI Technologies Inc.
- Is Modded: Definitely; 'forge,fml'
- Type: Client
- Texture Pack: Default
- Profiler Position: N/A (disabled)

cpw.mods.fml.common.LoaderException: java.lang.reflect.InvocationTargetException
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:102)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:445)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:141)
    at net.minecraft.client.Minecraft.a(Minecraft.java:405)
    at net.minecraft.client.Minecraft.run(Minecraft.java:737)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:371)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:81)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:444)
    ... 4 more
Caused by: java.lang.NoSuchMethodError: cpw.mods.fml.common.event.FMLPreInitializationEvent.getVersionProperties()Ljava/util/Properties;
    at cpw.mods.compactsolars.CompactSolars.preInit(CompactSolars.java:44)
    ... 29 more
--- END ERROR REPORT 84a62ac8 ----------

**Comment by aidancbrady** [comment]
Update Forge.  You're using an old version.
